### ISSUE TITLE
🗺️ Roadmap

### ISSUE THREAD

**Issue by axieax** [axieax/typo.nvim#1]
Plan for future features:

- [ ] Don't check typo upon selecting a corrected file (e.g. test/ --> test.lua --> test.lua.txt)
- [ ] Ignore if file already has a file extension (extensible ignore_condition)
- [ ] Check for similar spellings, not just filenames with the typo as a prefix
- [ ] Search for other similar filenames in the current working directory, e.g. different level of the same filename
- [ ] Option to not suggest directories

Completed features:

<details>
<summary>Show completed</summary>

</details>
